version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - my_network

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
